controllers/OrderinfoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrderInfo;
use app\models\OrderInfoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\ItemInfo;
use app\models\ItemInfoLiveSearch;
use app\models\ItemInfoOfflineSearch;
use app\models\OrderItemInfo;
use app\modules\users\models\Userdetail;
use yii\data\Pagination;
use yii\helpers\Url;
/**
 * OrderinfoController implements the CRUD actions for OrderInfo model.
 */
class OrderinfoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
	

	public function beforeAction($event)
    {
        $this->enableCsrfValidation = false;
		$before_login_action=array();
		$after_login_action=array();
		$before_login_action=array('checkchef','review');

		$action=Yii::$app->controller->action->id;
		$allow_action=false;
		// check is user loged in 
		if(Yii::$app->user->isGuest){
			if(in_array($action,$before_login_action)) $allow_action=true;
		}else{
			$allow_action=true;
		}
		
		if(!$allow_action){
			 return $this->goHome();
		}else{
			return parent::beforeAction($event);
		}
    }
	
    /**
     * Lists all OrderInfo models.
     * @return mixed
     */
 

	public function actionIndex()
    {
        $searchModel = new OrderInfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		
		
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	public function actionIndex2()
    {
        $searchModel = new OrderInfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index2', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	
	
    /**
     * Displays a single OrderInfo model.
     * @param integer $id
     * @return mixed
     */
	 
	 
    public function actionCheckchef()
    {
	//	session_start();
		$itemid=0;
		$itemid=$_POST['item_id'];
		$item_info = ItemInfo::find()->where([ 'id'=>$itemid,'status'=>1])->one();
		if(count($item_info)>0){
			$item_chef=$item_info->chef_user_id;
			$item_quantity=$item_info->quantity;
			if($item_quantity>0){
				if(isset($_SESSION['master_chef']) and ($_SESSION['master_chef']>0)){
					if($_SESSION['master_chef']!=$item_chef){
						return false;
					}
				}
				if(Yii::$app->user->id==$item_chef){
					return 4;
				}
				
				return true;
			}else{
				return 3;	
			}
			
		}
	}	
	 
	
		 
		 
    public function Deleteitem($itemid)
    {			
		if(isset($_SESSION['order_array'])){
			$old_session_items=$_SESSION['order_array']['order_item'];	
			unset($old_session_items[$itemid]);
			$_SESSION['order_array']['order_item']=$old_session_items;  

			return $old_session_items;    
		}	
	}		
	
    public function Additemtoorder($itemid)
    {
		
		$item_id=0;
		$item_qty=0;
		$item_price=0;
		$item_chef=0;
		$item_quantity=0;
		$item_name=null;
		$item_ingredients=null;
		$item_chef_name=null;
		$item_cuisine_type=null;
		
		$item_array=array();
		$old_session_items=array();
		if(isset($_SESSION['order_array'])){
			$old_session_items=$_SESSION['order_array']['order_item'];	
		}		
		$item_image=Url::to('@web/fuberme/images/default_item_image.jpg');
		$item_info = ItemInfo::find()->where([ 'id'=>$itemid,'status'=>1])->one();
		if(count($item_info)>0){
			$item_id=$item_info->id;
			$item_qty=1;
			$item_price=$item_info->price;
			$item_chef=$item_info->chef_user_id;
			$item_chef_name=$item_info->chefUser->username;
			$item_name=$item_info->name;			
			$item_chef_quantity=$item_info->quantity;			
			$item_cuisine_type=$item_info->cuisineTypeInfo->name;

			if($item_info->ingredients!=null) {
				$item_ingredients=$item_info->ingredients;	
			}
			if($item_info->image!=null){
			  $item_image=Url::to('@web/fuberme/'.$item_chef.'/item_images/'.$item_info->image);
			}	

			$item_array=array($itemid=>array('item_id'=>$item_id,'item_name'=>$item_name,
											'item_qty'=>$item_qty,'item_price'=>$item_price,
											'item_ingredients'=>$item_ingredients,'item_cuisine_type'=>$item_cuisine_type,
											'item_chef_name'=>$item_chef_name,'item_chef'=>$item_chef,'item_image'=>$item_image
											,'item_chef_quantity'=>$item_chef_quantity
										));			
		}

		if(count($old_session_items)>0){
			$item_array=$old_session_items+$item_array;
		}else{
			if(count($item_array)>0){
				unset($_SESSION['master_chef']);
				unset($_SESSION['master_chef_name']);
				$_SESSION['master_chef']=$item_array[$itemid]['item_chef'];
				$_SESSION['master_chef_name']=$item_array[$itemid]['item_chef_name'];
			}
		}		
	
		return $item_array;    
	}	
	 
	 
	public function  UpdateAmount(){
		
		$order_array=$_SESSION['order_array'];

		$order_item_array=null;
		$order_item_array=$order_array['order_item'];
		$tax_in_percent=$order_array['tax_in_percent'];
		$get_price=array();
		if(count($order_item_array)>0){
			foreach($order_item_array as $value){
				$get_price[]=$value['item_price']*$value['item_qty'];
			}
			
			$total_amount=0;
			$final_amount=0;			
			$final_amount_per=0;			
			$tax_in_percent_amount=0;			
			$total_amount=array_sum($get_price);
			$total_amount=number_format((float)$total_amount, 2, '.', '');
			
			$final_amount=$total_amount;		
			if($tax_in_percent>0){			
				$final_amount_per=($total_amount*$tax_in_percent)/100;
				$final_amount_per=$final_amount_per+0.30;
				$final_amount=$total_amount+$final_amount_per;
				$final_amount=number_format((float)$final_amount, 2, '.', '');
				$tax_in_percent_amount=number_format((float)$final_amount_per, 2, '.', '');  //$final_amount_per;
			}

			$_SESSION['order_array']['total_amount']=$total_amount;
			$_SESSION['order_array']['final_amount']=$final_amount;
			$_SESSION['order_array']['tax_in_percent_amount']=$tax_in_percent_amount;
		}

		
	}
	 
	 
    public function actionChangeqty()
    {
		session_start();
		$item_id=$_POST['item_id'];
		$new_qty=$_POST['new_qty'];
		if(isset($_SESSION['order_array'])){
			$_SESSION['order_array']['order_item'][$item_id]['item_qty']=$new_qty;
			$this->UpdateAmount();
			$norder_array=array('tax_in_percent_amount'=>$_SESSION['order_array']['tax_in_percent_amount'],'total_amount'=>$_SESSION['order_array']['total_amount'],'final_amount'=>$_SESSION['order_array']['final_amount']);
			echo $json = json_encode($norder_array);
		}

	}
	 
    public function actionReview($itemid)
    {

		// Buil session here
		$order_array=array();	
		$item_info=array();	
		$customer_name=null;
		$customer_email=null;
		$customer_address=null;
		$customer_city=null;
		$customer_state=null;
		$customer_zip=null;
		$customer_mobile_no=null;
		$payment_method=null;
		$delivery_method=null;
		$tax_in_percent=0;
		$tax_in_percent_amount=0;
		$item_chef=0;
		$customer_id=0;
			
		$user_id=Yii::$app->user->id;	
		$user_info = Userdetail::find()->where([ 'id'=>$user_id,'status'=>1 ])->one();
		if(count($user_info)>0){
			$customer_id=$user_info->id;
			$customer_name=$user_info->username;
			$customer_email=$user_info->email_id;
			$customer_mobile_no=$user_info->mobile_number;
			$customer_address=$user_info->address;
			$customer_city=$user_info->city;
			$customer_state=$user_info->state;
			$customer_zip=$user_info->zipcode;
		}

		$item_info=$this->Additemtoorder($itemid);
		$item_chef=$item_info[$itemid]['item_chef'];
		if(count($item_chef)>0){
		$chef_info = Userdetail::find()->where([ 'id'=>$item_chef,'status'=>1 ])->one();
			if(count($chef_info)>0){
				$payment_method=$chef_info->payment_method;
				$delivery_method=$chef_info->delivery_method;
			}
		}
		
		
		if($payment_method!=null and $payment_method=='paypal'){
			$tax_in_percent=2.9;	
		}
		
		
	//	if(isset($_GET['directorder']) and $_GET['directorder']>0){
		if(isset($_SESSION['order_array']['order_item'])){

			$order_items=$_SESSION['order_array']['order_item'];
			if(count($order_items)>0){
				foreach($order_items as $order_item){					
					$chef_id=$order_item['item_chef'];
					if(Yii::$app->user->id==$chef_id){
						$ditem=$order_item['item_id'];
						$item_info=$this->Deleteitem($ditem);
					}
				}
			}
		}

		// delete item		
		if(isset($_GET['ditem']) and $_GET['ditem']>0){
			$ditem=$_GET['ditem'];
			$item_info=$this->Deleteitem($ditem);
		}
		
		
		
		$order_array['customer_info']=array('customer_id'=>$customer_id,'customer_name'=>$customer_name,
								'customer_email'=>$customer_email,'customer_address'=>$customer_address,
								'customer_city'=>$customer_city,'customer_state'=>$customer_state,
								'customer_zip'=>$customer_zip,'customer_mobile_no'=>$customer_mobile_no); 
		$order_array['order_item']=$item_info;
		$order_array['payment_method']=$payment_method;
		$order_array['delivery_method']=$delivery_method;
		$order_array['tax_in_percent']=$tax_in_percent;
		$order_array['tax_in_percent_amount']=$tax_in_percent_amount;
		$order_array['total_amount']=0;			// Function for calculate total amount
		$order_array['final_amount']=0;			// Function for calculate total amount
		

		$_SESSION['order_array'] = $order_array;


		$item_info=$this->UpdateAmount();
		

		//update offline live items
		// Call functtion for to update item 
		Yii::$app->mediacomponent->Updateitemstatus();	
		//update offline live items
		
		
		
		if(isset($_SESSION['master_chef']) and $_SESSION['master_chef']>0){
			$chef_array[]=$_SESSION['master_chef'];
			if($chef_array!=null){
				$_SESSION['filetrsarray']=array(
											'min_location'=>1,
											'max_location'=>1,
											'chef_array'=>$chef_array,
											'search_by_item'=>null,
											'min_price'=>0,
											'max_price'=>0,

views/site/_view.php
<?php
use yii\helpers\Html;
$user_id=$model->chef_user_id;
?>

					<a href="<?php echo Yii::$app->homeUrl; ?>?r=iteminfo/update&id=<?php echo $model->id; ?>"><div class="product-grid love-grid">
						<div class="more-product"><span> </span></div>						
						<div class="product-img b-link-stripe b-animate-go  thickbox">
							<?php if($model->image==null){ ?>
								<img src="<?php echo  yii\helpers\Url::to('@web/fuberme/images/default_item_image.jpg'); ?>"  alt="item image">
							<?php }else{ ?>
								<img src="<?php echo  yii\helpers\Url::to('@web/fuberme/'.$user_id.'/item_images/'.$model->image); ?>" alt="FuberMe">
							<?php } ?>
								
						<!--	<div class="b-wrapper">
							<h4 class="b-animate b-from-left  b-delay03">							
							<button class="btns"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>Quick View</button>
							</h4>
							</div>  -->
						</div></a>						
						<div class="product-info simpleCart_shelfItem">
							<div class="product-info-cust" style="width: 350px;">
								<div class="col-md-6" style="padding: 0; height: 60px;">
								<h4><?php echo $model->name; ?></h4>
								<p><?php echo $model->chefUser->username; ?></p>
								</div>
								
								<div class="col-md-6" style="text-align: right;padding: 0; height: 60px;">
								<span class="item_price">$<?php echo $model->price; ?></span><br/>								
								</div>
								
								
								<?php /*
								<p>Availability : <br/><?php echo $model->availability_from_date.' '.Yii::$app->params['time_piker'][$model->availability_from_time]; ?>
								- <?php echo $model->availability_to_date.' '.Yii::$app->params['time_piker'][$model->availability_to_time]; ?></p>
								*/ ?>

								<?php // yii\helpers\Html::a('<span class="glyphicon glyphicon-edit"></span>',['update','id'=>$model->id],['class'=>'item_add items','data-toggle'=>'tooltip','data-placement'=>'top','title'=>'Edit'] ) ?> 
								<?php // yii\helpers\Html::a('<span class="glyphicon glyphicon-trash"></span>',['delete','id'=>$model->id], ['onclick' => 'return confirm("Are you sure you want to delete this '.$model->name.' ?");','class'=>'item_add items','data-toggle'=>'tooltip','data-placement'=>'top','title'=>'Delete']) ?>
								<?php
								// echo date_default_timezone_get(); 

/* 								echo date("H:i:sa");
								 echo '<br/>';
								 echo $model->availability_from_time;
								 echo '<br/>';
								 echo $model->availability_to_time;  */
								// echo $newhours = date("H");
								$newdate = date("d-M-Y");
								$newdates = strtotime($newdate);
								$availability_to_date = strtotime($model->availability_to_date);
								$availability_from_date = strtotime($model->availability_from_date);
								$newhours = date("H");
								$newminiute = date("i");		
								//if($newminiute>=0 and $newminiute<=30) $newminiute = 00;
								//if($newminiute>=30 and $newminiute<=60) $newminiute = 30;
								$newTime = $newhours.':'.$newminiute;
								$newTime = strtotime($newTime); 
								$availability_from_time = strtotime($model->availability_from_time); 
								$availability_to_time = strtotime($model->availability_to_time); 
								
								$display_offline=0;
								if($availability_from_date<=$newdates and $newdates<=$availability_to_date){
									if($availability_from_date!=$newdates and $newdates!=$availability_to_date){
										$display_offline=1;
									}elseif($availability_from_date==$newdates and $newdates!=$availability_to_date){
										$display_offline=1;
									}else{
										if($availability_from_date==$newdates and ($newTime>=$availability_from_time and $availability_to_time>=$newTime)){
											$display_offline=1;
										}
										if($availability_to_date==$newdates and $newTime>=$availability_from_time and $availability_to_time>=$newTime){
											$display_offline=1;
										}
									}
								}
								
								if($display_offline==1){  
								?>	
									<div class="itemerrorclass itemerror<?php echo $model->id; ?>"></div>
										<?= yii\helpers\Html::a('Order Now <span class="glyphicon glyphicon-chevron-right"></span>',['/orderinfo/review','itemid'=>$model->id],['id'=>$model->id,'class'=>'item_add items placeorder']) ?>
									
								<?php }else{ ?>								
								   <?= yii\helpers\Html::a('<span class="glyphicon glyphicon-ban-circle"></span>&nbsp;&nbsp;Currently Offline','#',['class'=>'item_add','style'=>'background: lightgray;color: red;']) ?>
								  
								<?php } ?>
							</div>													
							<div class="clearfix"> </div>
						</div>
					</div>



		

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/cart.php
<div class="cart_main">
	 <div class="container">
			 <ol class="breadcrumb">
		  <li><a href="men.html">Home</a></li>
		  <li class="active">Cart</li>
		 </ol>			
		 <div class="cart-items">
			 <h2>My Shopping Bag (2)</h2>
				<script>$(document).ready(function(c) {
					$('.close1').on('click', function(c){
						$('.cart-header').fadeOut('slow', function(c){
							$('.cart-header').remove();
						});
						});	  
					});
			   </script>
			 <div class="cart-header">
				 <div class="close1"> </div>
				 <div class="cart-sec">
						<div class="cart-item cyc">
							 <img src="../vendor/bower/fuberme/images/ts4.jpg"/>
						</div>
					   <div class="cart-item-info">
							 <h3>Posuere cubilia Curae<span>Duis vehicula sodales </span></h3>
							 <h4><span>Rs. </span>150.00</h4>
					   </div>
					   <div class="clearfix"></div>
						<div class="delivery">
							 <p>Service Charges:: Rs.50.00</p>							 
				        </div>						
				  </div>
			 </div>
			 <script>$(document).ready(function(c) {
					$('.close2').on('click', function(c){
							$('.cart-header2').fadeOut('slow', function(c){
						$('.cart-header2').remove();
					});
					});	  
					});
			 </script>
			 <div class="cart-header2">
				 <div class="close2"> </div>
				  <div class="cart-sec">
						<div class="cart-item">
							 <img src="../vendor/bower/fuberme/images/ts1.jpg"/>
						</div>
					   <div class="cart-item-info">
							 <h3>Vitae viverra<span>Duis vehicula sodales </span></h3>
							 <h4><span>Rs. </span>200.00</h4>
					   </div>
					   <div class="clearfix"></div>
						<div class="delivery">
							 <p>Service Charges:: Rs.50.00</p>							
				        </div>						
				  </div>
			  </div>		
		 </div>
		 
		 <div class="cart-total">
			 <a class="continue" href="#">Continue to Order</a>
			 <div class="price-details">
				 <h3>Price Details</h3>
				 <span>Total</span>
				 <span class="total">350.00</span>
				 <span>Discount</span>
				 <span class="total">---</span>
				 <span>Delivery Charges</span>
				 <span class="total">100.00</span>
				 <div class="clearfix"></div>				 
			 </div>	
			 <h4 class="last-price">TOTAL</h4>
			 <span class="total final">450.00</span>
			 <div class="clearfix"></div>
			 <a class="order" href="#">Place Order</a>
			 <br/>
<!-- 			 <div class="total-item">
				 <h3>OPTIONS</h3>
				 <h4>COUPONS</h4>
				 <a class="cpns" href="#">Apply Coupons</a>
				 <p><a href="#">Log In</a> to use accounts - linked coupons</p>
			 </div> -->
			</div>
	 </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index1.php
<br/><br/><br/>

<!---->
<div class="container">

	 <div class="registration">
					<br/><br/><br/><br/>
					<center><h2>Website is under regular maintenance. <br/> <br/>
				We will be live soon.
					</h2></center>
		
		 <div class="clearfix"></div>
	 </div>
</div>


<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>



<!---->
<div class="login_sec">
	 <div class="container">
		 <ol class="breadcrumb">
		  <li><a href="index.html">Home</a></li>
		  <li class="active">Login</li>
		 </ol>
		 <h2>Login</h2>
		 <div class="col-md-6 log">			 
				 <p>Welcome, please enter the folling to continue.</p>
				 <p>If you have previously Login with us, <span>click here</span></p>
				 
				 <form>
					 <h5>User Name:</h5>	
					 <input type="text" value="">
					 <h5>Password:</h5>
					 <input type="password" value="">					
					 <input type="submit" value="Login">
					  <a href="#">Forgot Password ?</a>
				 </form>	
				 
				 
					<?php /* $form = ActiveForm::begin([
						'id' => 'login-form',
						'options' => ['class' => 'form-horizontal'],
						'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
						],
					]); ?>

						<?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

						<?= $form->field($model, 'password')->passwordInput() ?>

						<?= $form->field($model, 'rememberMe')->checkbox([
							'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
						]) ?>

						<div class="form-group">
							<div class="col-lg-offset-1 col-lg-11">
								<?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
							</div>
						</div>

					<?php ActiveForm::end();*/ ?>		 
		 </div>
		  <div class="col-md-6 login-right">
			  	<h3>NEW REGISTRATION</h3>
				<p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
				<a class="acount-btn" href="account.html">Create an Account</a>
		 </div>
		 <div class="clearfix"></div>
	 </div>
</div>

views/site/thanku.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\users\models\Userdetail */
/* @var $form yii\widgets\ActiveForm */


?>


<br/><br/><br/>

<!---->
<div class="container">

	 <div class="registration">
					<br/><br/><br/><br/>
					<center><h2>Thank you for registering as an Early Bird! <br/>
					Please verify your email before logging in.
					</h2></center>
		
		 <div class="clearfix"></div>
	 </div>
</div>


<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>

views/site/thankupass.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>


<br/><br/><br/>

<!---->
<div class="container">

	 <div class="registration">
					<br/><br/><br/><br/>
					<center><h2>
						Please,Check Your Mail to reset Your password.
					</h2></center>
		
		 <div class="clearfix"></div>
	 </div>
</div>

<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>